# Generated by Django 3.1.7 on 2021-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmddel',
            name='content',
            field=models.TextField(max_length=700, verbose_name='Açıklama'),
        ),
    ]
