# Generated by Django 3.1.7 on 2021-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='İsim')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('people', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Kişi Sayısı')),
                ('message', models.TextField(max_length=600, verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
            },
        ),
    ]
