# Generated by Django 3.1.7 on 2021-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('unvan', models.CharField(max_length=100, verbose_name='Unvan')),
                ('image', models.ImageField(upload_to='chef/')),
            ],
            options={
                'verbose_name': 'Şef',
                'verbose_name_plural': 'Şefler',
            },
        ),
    ]
