# Generated by Django 3.1.7 on 2021-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Ad Soyad')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=75, verbose_name='Konu')),
                ('message', models.TextField(max_length=600, verbose_name='Mesaj')),

            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
            },
        ),
    ]
