# Generated by Django 3.1.7 on 2021-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField(max_length=600, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızdakiler',
            },
        ),
        migrations.CreateModel(
            name='WhyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField(max_length=600, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Neden Biz',
                'verbose_name_plural': 'Neden Biz',
            },
        ),
    ]
